Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2019-11, with the labels that each got.

#184 Misc small fixes to the docs
  .travis.yml
  doc/source/index.rst
  spinnman/get_cores_in_run_state.py
Labels: bug, minor

#185 Make the code to read system variables work with arrays
  spinnman/messages/spinnaker_boot/system_variable_boot_values.py
  spinnman/transceiver.py
Labels: bug, minor, question

#187 Max cores per chip
  spinnman/processes/get_machine_process.py
  spinnman/transceiver.py
Labels: enhancement

#189 hint:__str__ should return a string!
  spinnman/model/cpu_infos.py
Labels: bug
