Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2020-12, with the labels that each got.

#228 Update the sphinx version
  .github/workflows/python_actions.yml
  requirements-test.txt
Labels: Blocker!, bug

#223 Stable Time Sync
  spinnman/messages/spinnaker_boot/boot_data/scamp.boot
  spinnman/messages/spinnaker_boot/system_variable_boot_values.py
Labels: bug

#229 Add a method for the simple case of reading one word
  spinnman/transceiver.py
Labels: enhancement, minor

#230 Corrections to numpy version requirements
  requirements-test.txt
Labels: Blocker!, bug

#231 Convert to use new actions
  .github/workflows/python_actions.yml
  .travis.yml
Labels: enhancement, minor

#227 removed unused io functionality
  integration_tests/.gitignore
  integration_tests/__init__.py
  integration_tests/test_file_io.py
  integration_tests/test_memory_io.py
  spinnman/processes/__init__.py
  spinnman/processes/fill_process.py
  spinnman/transceiver.py
  spinnman/utilities/io/__init__.py
  spinnman/utilities/io/abstract_io.py
  spinnman/utilities/io/file_io.py
  spinnman/utilities/io/memory_io.py
Labels: enhancement
