Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2020-02, with the labels that each got.

#194 Increase retry
  spinnman/messages/scp/impl/flood_fill_end.py
  spinnman/messages/scp/impl/flood_fill_start.py
Labels: enhancement

#193 Count the correct thing!
  spinnman/transceiver.py
Labels: bug

#196 () → (void)
  hello.c
Labels: bug, minor

#195 Display any errors when a callback completes
  spinnman/connections/connection_listener.py
Labels: enhancement, minor

#198 Detect router errors
  spinnman/model/enums/router_error.py
  spinnman/model/router_diagnostics.py
Labels: enhancement

#197 fewer timeouts
  spinnman/connections/udp_packet_connections/udp_connection.py
Labels: enhancement
