Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2021-02, with the labels that each got.

#236 extra logging when things stall
  spinnman/transceiver.py
Labels: enhancement

#237 Config to shut up debug
  spinnman/transceiver.py
Labels: enhancement

#238 Test 3 9
  .github/workflows/python_actions.yml
  doc/source/conf.py
  setup.py
Labels: enhancement, minor

#240 Lost spike issues
  spinnman/messages/spinnaker_boot/boot_data/scamp.boot
Labels: bug

#241 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor
