Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2021-06, with the labels that each got.

#251 fixed process to work
  spinnman/get_cores_in_run_state.py
Labels: bug

#250 Deprecate unused methods
  spinnman/messages/scp/impl/bmp_set_led.py
  spinnman/messages/scp/impl/read_adc.py
  spinnman/messages/scp/impl/set_led.py
  spinnman/processes/de_alloc_sdram_process.py
  spinnman/transceiver.py
Labels: minor

#252 Unittest setup
  spinnman/config_setup.py
  unittests/connection_tests/test_udp_boot_connection.py
  unittests/connection_tests/test_udp_connection.py
  unittests/model_tests/test_abstract_process.py
  unittests/model_tests/test_core_subset_model.py
  unittests/model_tests/test_core_subsets_model.py
  unittests/model_tests/test_io_buff_model.py
  unittests/model_tests/test_iptag_model.py
  unittests/model_tests/test_machine_dimensions_model.py
  unittests/model_tests/test_retrieving_values_from_enum_models.py
  unittests/model_tests/test_version_info_model.py
  unittests/scp_tests/test_count_state_response.py
  unittests/scp_tests/test_scp_check_ok_response.py
  unittests/scp_tests/test_scp_enums.py
  unittests/scp_tests/test_scp_message_assembly.py
  unittests/scp_tests/test_scp_version_request.py
  unittests/scp_tests/test_scp_version_response.py
  unittests/sdp_tests/test_sdp_enums.py
  unittests/test_boot_message_assembly.py
  unittests/test_cfg_checker.py
  unittests/test_import_all_test.py
  unittests/test_multicast_message_assembly.py
  unittests/test_transceiver.py
  unittests/test_version.py
Labels: enhancement

#253 Catch any exceptions in hostname resolution
  spinnman/utilities/locate_connected_machine_ip_address.py
Labels: bug
