Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2021-04, with the labels that each got.

#244 Use Context Managers
  board_test_configuration.py
  quick_tests.py
  spinnman/connections/connection_listener.py
  spinnman/connections/udp_packet_connections/ip_address_connection.py
  spinnman/connections/udp_packet_connections/udp_connection.py
  spinnman/get_cores_in_run_state.py
  spinnman/processes/get_machine_process.py
  spinnman/transceiver.py
  spinnman/utilities/utility_functions.py
  unittests/test_transceiver.py
Labels: enhancement, minor

#243 Bump6.0.1
  doc/source/conf.py
  requirements.txt
  setup.py
  spinnman/_version.py
Labels: next_release

#245 Cfg stack
  spinnman/config_setup.py
  spinnman/spinnman.cfg
  unittests/test_cfg_checker.py
Labels: enhancement
