Repository SpiNNakerManchester/SpiNNMan, pull requests merged in 2022-05, with the labels that each got.

#278 Quick test fix
  quick_tests.py
Labels: bug, minor

#269 Whole
  spinnman/exceptions.py
  spinnman/model/chip_info.py
  spinnman/model/cpu_info.py
  spinnman/model/cpu_infos.py
  spinnman/processes/abstract_multi_connection_process.py
  spinnman/processes/abstract_multi_connection_process_connection_selector.py
  spinnman/processes/abstract_process.py
  spinnman/processes/abstract_single_connection_process.py
  spinnman/processes/most_direct_connection_selector.py
  spinnman/processes/round_robin_connection_selector.py
  spinnman/transceiver.py
  unittests/model_tests/test_abstract_process.py
Labels: enhancement

#267 Pylint fix
  .pylintrc
  spinnman/connections/scp_request_pipeline.py
  spinnman/connections/udp_packet_connections/ip_address_connection.py
  spinnman/connections/udp_packet_connections/udp_connection.py
  spinnman/processes/get_machine_process.py
  spinnman/transceiver.py
Labels: minor

#283 Small documentation fix
  spinnman/transceiver.py
Labels: bug, minor

#285 No P2PC command
  spinnman/messages/scp/enums/scp_command.py
  unittests/scp_tests/test_scp_enums.py
Labels: bug

#286 More error details
  spinnman/connections/scp_request_pipeline.py
  spinnman/exceptions.py
  spinnman/messages/scp/abstract_messages/scp_request.py
  spinnman/messages/scp/impl/app_copy_run.py
Labels: enhancement
